apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remoulade.fullname" . }}
  labels:
    {{- include "remoulade.labels" . | nindent 4 }}
spec:
  {{- if not .Values.superbowl.autoscaling.enabled }}
  replicas: {{ .Values.superbowl.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "remoulade.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.superbowl.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "remoulade.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.superbowl.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "remoulade.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.superbowl.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.superbowl.securityContext | nindent 12 }}
          image: "{{ .Values.superbowl.image.repository }}:{{ .Values.superbowl.image.tag | default .Chart.AppVersion }}"
          pullPolicy: {{ .Values.superbowl.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.superbowl.resources | nindent 12 }}
      {{- with .Values.superbowl.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.superbowl.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.superbowl.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
